# Generated by Django 2.2.12 on 2020-04-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='User name')),
                ('email', models.EmailField(max_length=50, verbose_name='User email')),
                ('password1', models.CharField(max_length=20, verbose_name='User password1')),
                ('password2', models.CharField(max_length=20, verbose_name='User password2')),
            ],
        ),
    ]
