# Generated by Django 2.2.12 on 2020-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='password1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
