# Generated by Django 2.2.12 on 2020-04-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200404_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerregistration',
            old_name='password1',
            new_name='password',
        ),
    ]
