# Generated by Django 2.2.12 on 2020-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200404_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistration',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
